### ISSUE TITLE
AsyncLock should implement IDisposable as it contains SemaphoreSlim

### ISSUE THREAD

**Issue by yuvalpeled1** [i3arnon/AsyncUtilities#5]
AsyncLock should implement IDisposable as it contains SemaphoreSlim which should be disposed.

**Comment by i3arnon** [comment]
The `Task` type also implements `IDisposable`.
Do you surround each `await` in your code with a `using` scope?

**Comment by i3arnon** [comment]
> If you access the AvailableWaitHandle property, then Yes, you must call Dispose() to cleanup unmanaged resources. 
If you do not access AvailableWaitHandle, then No, calling Dispose() won't do anything important.


https://stackoverflow.com/a/39195920/885318
